### ISSUE TITLE
NeuronInfo::stake is 0, when it shouldn't

### ISSUE THREAD

**Issue by ales-otf** [RaoFoundation/subtensor#925]
### Describe the bug

Sometimes rpc for `NeuronInfoApi` like, `get_neuron` and `get_neuron_lite`, returns `NeuronInfo::stake` 0 for all stakers. While there are stakes actually.

### To Reproduce

This happens when the registrar of the subnet has 0 stake. Independent of how much other neurons stake, they will be 0. 

One case, is when the registrar registering a subnet and don't stake afterward. If another neurons register and add stakes, the `NeuronInfo::stake` for all of them will be 0.

Another keys, is when the registrar stakes 0, after non-zero stake.

Staking 0 on other neurons doesn't affect other stakers.

### Expected behavior

Stakes should be calculated correctly.

### Environment

macOS, feat/rao-devnet-ready branch

### Additional context

Is it ok for `add_stake` extrinsic to allow staking 0?

**Comment by camfairchild** [comment]
This should be fixed by 4fc8cd6339adc25404c539fd241e2d051abfff2f

**Comment by ales-otf** [comment]
~~It's already fixed on `feat/rao-devnet-ready`~~ https://github.com/opentensor/subtensor/issues/925#issuecomment-2460945448

**Comment by gztensor** [comment]
Changing status to "In Review" because it is not deployed to Testnet, Devnet, or Mainnet.

**Comment by gztensor** [comment]
@camfairchild , could you please add a test for this as well?

**Comment by ales-otf** [comment]
I've been checking it against E2E `test_metagraph` test and found out that it's not fixed. 

Per the test it like this:

- register a subnet and don't stake by registrar
- register a neuron
- register another neuron
- stake by the second neuron

Both stakes are 0s.

Going further I discovered, that if I proceed and stake with the first neuron, the stake of the second's neuron becomes 0.

**Comment by distributedstatemachine** [comment]
@camfairchild are you going to change neuron info as well? this is what powers the metagraph IIRC
